policy_kwargs: {}
learning_rate: 0.0005
buffer_size: 100000
learning_starts: 10000
batch_size: 256
tau: 1.0
gamma: 0.99
train_freq: 4
target_update_interval: 2000
exploration_fraction: 0.1
exploration_final_eps: 0.05
gradient_steps: 1
