algo: dqn
learning_rate: 0.0005
buffer_size: 100000
learning_starts: 10000
batch_size: 128
tau: 1.0
gamma: 0.99
train_freq: 4
gradient_steps: 1
target_update_interval: 1000
exploration_fraction: 0.2
exploration_final_eps: 0.05
policy_kwargs:
  net_arch: [256, 256]